query tagTypeList ($input: TagInfoNameDTO)  {
  tagTypeList: tagSelectAllByTagType (input: $input) {
    ### 标签分类Id ###
    tagCategoryId
    ### 标签分类名称 ###
    tagCategoryName
    ### 标签分类权重 ###
    categoryOrder
    ### 标签返回值 ###
    results {
      ### tagId ###
      id
      ### tagObjectId ###
      tagObjectId
      ### tag名称 ###
      tagName
      ### 租户Id ###
      tenantId
      ### 该标签引用在表中数量 ###
      useCount
      ### 点赞数 ###
      praiseCount
      ### 当前用户是否对该标签点击过 true : 已点赞 ###
      voted
      ### 当前用户是否可以删除该标签 true : 可删除 ###
      removable
    }
  }
}