#import "./tech_manage_category_fragment.gql"
#import "./dbsource_fragment.gql"
#import "./tech_manage_schedule_fragment.gql"

query techDataList ($keyword: String)  {
  techDataList: mdsLoadTechCataData (keyword: $keyword) {
    id
    parentId
    level
    category {
      ...MdsCategory
    }
    dbSource {
      ...MdsDbSource
    }
    schedule {
      ...MdsSchedule
    }
  }
}